---
name: R-CMD-check

on:
  - push
  - pull_request

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest

    container:
      image: blcdsdockerregistry/bl-r-devel:latest

    steps:
      - uses: actions/checkout@v2
        with:
          path: SubclonePlot
      - run: R -e "install.packages('plyr')"
      - run: R CMD build --compact-vignettes="gs+qpdf" SubclonePlot
      - run: R CMD check --as-cran --run-donttest SubclonePlot_*.tar.gz
